### ISSUE TITLE
TimeStamp Verify problem 

### ISSUE THREAD

**Issue by ghost** [honsdomi/AbsoluteTimestamp#1]
Hi I have problem with verifing timesamp.  I created timestamp succesfuly and save the timestamp.Timestamp byte array. My problem is verifying timestamp. Im sending verify functiond to diffrenet data with  old Timestamp byte array  and it verifying. What I'm tring to do is prove the data isnt changed . Here is my code ;

  TimestampVerifier verifier = new TimestampVerifier();
                TimestampObject verifiedTimestamp = verifier
                    .SetTimestampedData("hello world 2") 
                    .SetHashAlgorithm(HashAlgorithm.SHA512)
                    .SetTimestamp(FirstTsa.Timestamp) ------>this time stamp created with data as "test data "
                    .Verify();

**Comment by honsdomi** [comment]
Hi. The issue you are describing is covered by a test. See `TestVerifyWrongTimestampData` [here](https://github.com/honsdomi/AbsoluteTimestamp/blob/master/AbsoluteTimestampTests/TimestampVerifierTest.cs).
